[package]
name = "quri-ui"
description = "quri is the Light Weight Database Client built on GPUI for Maximum Performance"
version.workspace = true
edition.workspace = true

[dependencies]
# quri
quri-core = { path = "../quri-core" }
quri-storage = { path = "../quri-storage" }

# gpui
gpui = { git = "https://github.com/zed-industries/zed" }
gpui_platform = { git = "https://github.com/zed-industries/zed", features = ["wayland", "x11"] }
gpui-component = { git = "https://github.com/longbridge/gpui-component", features = ["tree-sitter-sql"] }
gpui-component-assets = { git = "https://github.com/longbridge/gpui-component" }

# serde
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

anyhow = "1.0"
async-trait = "0.1"
tokio = "1.47.1"
tracing = "0.1"

image = "0.25.10"
rust-embed = "8.11.0"
